-- MySQL Script generated by MySQL Workbench
-- Tue May  6 01:59:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `doctor_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `crm_number` VARCHAR(45) NULL,
  PRIMARY KEY (`doctor_id`, `user_id`),
  INDEX `fk_doctor_user_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `doctor_id_UNIQUE` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caregiver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`caregiver` (
  `caregiver_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`caregiver_id`, `user_id`),
  INDEX `fk_caregiver_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `caregiver_id_UNIQUE` (`caregiver_id` ASC) VISIBLE,
  CONSTRAINT `fk_caregiver_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`serena_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`serena_device` (
  `serena_device_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`serena_device_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Senior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Senior` (
  `senior_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  `caregiver_caregiver_id` INT NOT NULL,
  `caregiver_user_id` INT NOT NULL,
  `age` INT NOT NULL,
  `serena_device_serena_device_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`senior_id`, `user_user_id`),
  INDEX `fk_Senior_user1_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_Senior_caregiver1_idx` (`caregiver_caregiver_id` ASC, `caregiver_user_id` ASC) VISIBLE,
  UNIQUE INDEX `senior_id_UNIQUE` (`senior_id` ASC) VISIBLE,
  UNIQUE INDEX `caregiver_caregiver_id_UNIQUE` (`caregiver_caregiver_id` ASC) VISIBLE,
  INDEX `fk_Senior_serena_device1_idx` (`serena_device_serena_device_code` ASC) VISIBLE,
  CONSTRAINT `fk_Senior_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Senior_caregiver1`
    FOREIGN KEY (`caregiver_caregiver_id` , `caregiver_user_id`)
    REFERENCES `mydb`.`caregiver` (`caregiver_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Senior_serena_device1`
    FOREIGN KEY (`serena_device_serena_device_code`)
    REFERENCES `mydb`.`serena_device` (`serena_device_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prescription` (
  `prescription_id` INT NOT NULL AUTO_INCREMENT,
  `doctor_doctor_id` INT NOT NULL,
  `doctor_user_id` INT NOT NULL,
  `Senior_senior_id` INT UNSIGNED NOT NULL,
  `Senior_user_user_id` INT NOT NULL,
  `create_time` VARCHAR(45) NULL,
  `validation_time` DATE NULL,
  PRIMARY KEY (`prescription_id`),
  INDEX `fk_prescription_doctor1_idx` (`doctor_doctor_id` ASC, `doctor_user_id` ASC) VISIBLE,
  INDEX `fk_prescription_Senior1_idx` (`Senior_senior_id` ASC, `Senior_user_user_id` ASC) VISIBLE,
  UNIQUE INDEX `prescription_id_UNIQUE` (`prescription_id` ASC) VISIBLE,
  UNIQUE INDEX `doctor_doctor_id_UNIQUE` (`doctor_doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_prescription_doctor1`
    FOREIGN KEY (`doctor_doctor_id` , `doctor_user_id`)
    REFERENCES `mydb`.`doctor` (`doctor_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_Senior1`
    FOREIGN KEY (`Senior_senior_id` , `Senior_user_user_id`)
    REFERENCES `mydb`.`Senior` (`senior_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disease` (
  `disease_type_id` INT NOT NULL,
  `disease_name` VARCHAR(126) NOT NULL,
  PRIMARY KEY (`disease_type_id`),
  UNIQUE INDEX `disease_name_UNIQUE` (`disease_name` ASC) VISIBLE,
  UNIQUE INDEX `disease_type_id_UNIQUE` (`disease_type_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disease_diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disease_diagnosis` (
  `disease_diagnosis_id` INT NOT NULL,
  `disease_disease_type_id` INT NOT NULL,
  `Senior_senior_id` INT UNSIGNED NOT NULL,
  `Senior_user_user_id` INT NOT NULL,
  `diagnosed_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`disease_diagnosis_id`),
  INDEX `fk_disease_diagnosis_disease1_idx` (`disease_disease_type_id` ASC) VISIBLE,
  INDEX `fk_disease_diagnosis_Senior1_idx` (`Senior_senior_id` ASC, `Senior_user_user_id` ASC) VISIBLE,
  UNIQUE INDEX `disease_diagnosis_id_UNIQUE` (`disease_diagnosis_id` ASC) VISIBLE,
  CONSTRAINT `fk_disease_diagnosis_disease1`
    FOREIGN KEY (`disease_disease_type_id`)
    REFERENCES `mydb`.`disease` (`disease_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disease_diagnosis_Senior1`
    FOREIGN KEY (`Senior_senior_id` , `Senior_user_user_id`)
    REFERENCES `mydb`.`Senior` (`senior_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medication` (
  `medication_id` INT NOT NULL AUTO_INCREMENT,
  `medication_name` VARCHAR(100) NULL,
  `form` VARCHAR(100) NULL,
  `concentration` VARCHAR(100) NULL,
  `description` TEXT(200) NULL,
  PRIMARY KEY (`medication_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prescription_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prescription_item` (
  `prescription_item_id` INT NOT NULL AUTO_INCREMENT,
  `medication_medication_id` INT NOT NULL,
  `dosage` VARCHAR(100) NOT NULL,
  `frequency_unit` ENUM("dia", "semana", "mes") NULL,
  `frequency_time` INT NULL,
  `duration_unit` ENUM("dia", "semana", "mes") CHARACTER SET 'ascii' NULL,
  `duration_time` INT NULL,
  `prescription_prescription_id` INT NOT NULL,
  `description` TEXT(100) NULL,
  PRIMARY KEY (`prescription_item_id`, `medication_medication_id`),
  UNIQUE INDEX `prescription_item_id_UNIQUE` (`prescription_item_id` ASC) VISIBLE,
  INDEX `fk_prescription_item_medication1_idx` (`medication_medication_id` ASC) VISIBLE,
  INDEX `fk_prescription_item_prescription1_idx` (`prescription_prescription_id` ASC) VISIBLE,
  CONSTRAINT `fk_prescription_item_medication1`
    FOREIGN KEY (`medication_medication_id`)
    REFERENCES `mydb`.`medication` (`medication_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_item_prescription1`
    FOREIGN KEY (`prescription_prescription_id`)
    REFERENCES `mydb`.`prescription` (`prescription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`complaint` (
  `complaint_id` INT NOT NULL AUTO_INCREMENT,
  `syptom` VARCHAR(100) NOT NULL,
  `serena_llm_response` TEXT(500) NULL,
  `create_time` VARCHAR(45) NULL,
  `Senior_senior_id` INT NOT NULL,
  `Senior_user_user_id` INT NOT NULL,
  PRIMARY KEY (`complaint_id`),
  UNIQUE INDEX `complaint_id_UNIQUE` (`complaint_id` ASC) VISIBLE,
  INDEX `fk_complaint_Senior1_idx` (`Senior_senior_id` ASC, `Senior_user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_complaint_Senior1`
    FOREIGN KEY (`Senior_senior_id` , `Senior_user_user_id`)
    REFERENCES `mydb`.`Senior` (`senior_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
